import { test, expect, mock } from 'bun:test';
import { readFileSync } from 'node:fs';
import { defaults } from '../public/profile.js';

test('agent editor saves across sections, retains failed drafts, and preserves inherited settings', async () => {
  const html = readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
  const dialogMarkup = html.slice(html.indexOf('<dialog id="customize-dialog"'),html.indexOf('<div id="toast"'));
  const node = () => ({hidden:false,disabled:false,value:'',textContent:'',innerHTML:'',dataset:{},style:{setProperty(){}},classList:{toggle(){}},focus(){document.activeElement=this;},setAttribute(key,value){this[key]=value;},removeAttribute(key){delete this[key];}});
  const nodes = new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(([,id])=>['#'+id,node()]));
  const panels = [...dialogMarkup.matchAll(/data-profile-step="(\d)"/g)].map(([,step])=>({...node(),dataset:{profileStep:step}}));
  const sections = [...dialogMarkup.matchAll(/data-custom-step="(\d)"/g)].map(([,step])=>({...node(),dataset:{customStep:step}}));
  const fields = new Map([...Object.keys(defaults),'overrideWorkspace'].map(name=>[name,node()]));
  for (const [id,name] of [['agent-name-input','name'],['owner-name-input','ownerName'],['agent-specialization','specialization'],['user-context-input','userContext'],['workspace-override','overrideWorkspace']]) nodes.set('#'+id,fields.get(name));
  for (const selector of ['.profile-layout','.profile-sidebar']) nodes.set(selector,node());
  const form=nodes.get('#customize-form'), dialog=nodes.get('#customize-dialog'), checkbox=fields.get('overrideWorkspace'), name=fields.get('name');
  form.elements={namedItem:key=>fields.get(key)};
  form.reset=()=>{};
  form.querySelectorAll=selector=>selector==='details' ? [] : [...sections,...['customize-save','customize-cancel','customize-defaults'].map(id=>nodes.get('#'+id))];
  name.closest=selector=>selector==='[data-profile-step]' ? panels.find(panel=>panel.dataset.profileStep==='1') : null; name.reportValidity=()=>{};
  form.querySelector=()=>name.value ? null : name;
  dialog.dispatchEvent=()=>{}; dialog.showModal=()=>{dialog.open=true;}; dialog.close=()=>{dialog.open=false;}; nodes.get('#settings-dialog').close=()=>{};
  const select=selector=>selector.startsWith('#customize-form select[name=') ? fields.get(selector.match(/name="([^"]+)"/)[1]) : nodes.get(selector);
  const previousDocument=globalThis.document, previousFormData=globalThis.FormData;
  globalThis.document={querySelector:select,querySelectorAll:selector=>selector==='[data-profile-step]' ? panels : selector==='[data-custom-step]' ? sections : []};
  globalThis.FormData=class { *[Symbol.iterator](){for(const [key,field] of fields) if(!field.disabled && key!=='overrideWorkspace') yield [key,field.value];} };
  const requests=[]; let fail=false;
  mock.module('../public/ui.js',()=>({$:select,api:async(url,body,method)=>{requests.push({url,body,method});if(fail)throw Error('Save failed');return body;},toast(){}}));
  const {setupCustomization,openCustomization}=await import('../public/customize.js');
  const state={agentId:'scout',agents:[{id:'scout'}],customization:{...defaults,name:'Scout'},appearance:{palette:'fern',motion:'reduced'},owner:{ownerName:'Alex',language:'id',detail:'brief',userContext:'Shared background'}};
  const submit=async()=>{form.onsubmit({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));};
  const change=()=>form.oninput();
  try {
    setupCustomization(()=>state,async result=>{state.customization=result;});
    openCustomization();
    expect(sections.map(section=>section.dataset.customStep)).toEqual(['1','0','2','3']);
    expect(panels.find(panel=>panel.dataset.profileStep==='1').hidden).toBe(false);
    expect(nodes.get('#customize-save').hidden).toBe(false); expect(document.activeElement).toBe(name);
    sections.find(section=>section.dataset.customStep==='2').onclick();
    expect(sections.find(section=>section.dataset.customStep==='2')['aria-current']).toBe('page');
    expect(fields.get('ownerName').disabled).toBe(true); expect(fields.get('ownerName').value).toBe('Alex');
    checkbox.checked=true;change(); fields.get('ownerName').value='Captain';change();
    checkbox.checked=false;change(); expect(fields.get('ownerName').value).toBe('Alex');
    checkbox.checked=true;change(); expect(fields.get('ownerName').value).toBe('Captain');
    name.value='';await submit();expect(requests).toHaveLength(0);expect(document.activeElement).toBe(name);
    expect(panels.find(panel=>panel.dataset.profileStep==='1').hidden).toBe(false);
    name.value='Updated Scout';fields.get('shape').value='fox';fields.get('bodyColor').value='#81ae76';change();
    sections.find(section=>section.dataset.customStep==='0').onclick();fail=true;await submit();
    expect(dialog.open).toBe(true);expect(nodes.get('#customize-status').textContent).toBe('Save failed');
    expect(name.value).toBe('Updated Scout');expect(nodes.get('#customize-save').disabled).toBe(false);
    fail=false;await submit();expect(dialog.open).toBe(false);
    expect(requests.at(-1)).toMatchObject({url:'/api/customization?agentId=scout',method:'PUT',body:{name:'Updated Scout',shape:'fox',bodyColor:'#81ae76',ownerName:'Captain',overrideWorkspace:true}});
    openCustomization();checkbox.checked=false;change();await submit();
    expect(requests.at(-1).body.ownerName).toBe('Captain');expect(requests.at(-1).body.overrideWorkspace).toBe(false);
    openCustomization(false,true);await submit();expect(requests.at(-1).url).toBe('/api/agents');
    openCustomization(false,false,false,true);expect(nodes.get('.profile-sidebar').hidden).toBe(false);
    expect(nodes.get('#customize-save').hidden).toBe(false);
    openCustomization(true,false,true);expect(nodes.get('#agent-appearance-controls').hidden).toBe(true);
    expect(nodes.get('#workspace-override-fields').hidden).toBe(false);expect(nodes.get('#customize-save').hidden).toBe(false);
  } finally {globalThis.document=previousDocument;globalThis.FormData=previousFormData;mock.restore();}
});
