import { test, expect } from 'bun:test';
import { EventEmitter } from 'node:events';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { chromium } from 'playwright';
import { createApp } from '../server.js';
import { defaults } from '../public/profile.js';

class RoomAI extends EventEmitter {
  child = {}; calls = []; replies = [];
  async request(method,params) {
    this.calls.push({method,params});
    if (method === 'account/read') return {account:{type:'chatgpt',planType:'pro'}};
    if (method.startsWith('thread/')) return {thread:{id:params.threadId || randomUUID()}};
    if (method === 'turn/start') return {turn:{id:randomUUID(),status:'inProgress'}};
    return {};
  }
  respond(id,result) { this.replies.push({id,result}); }
  reject() {}
  stop() {}
}

test('conversation rooms create, discuss, target agents, stop, edit, and survive reload on mobile', async () => {
  const directory = mkdtempSync(join(tmpdir(),'odwyn-room-ui-')), first = new RoomAI(), second = new RoomAI();
  let app;
  const server = Bun.serve({hostname:'127.0.0.1',port:0,fetch:(req,srv)=>app.fetch(req,srv)});
  app = createApp({directory,user:'owner',password:'test-password-long-enough',origin:server.url.origin,codex:first,browser:{close:async()=>{}}});
  app.runtime.state.customization = {...defaults,name:'Pip'}; app.runtime.state.provider.configured = true;
  const primary = app.runtime.state.agents[0].id;
  const request = async (path,body) => {
    const response = await app.fetch(new Request(new URL(path,server.url),{method:'POST',headers:{authorization:'Basic '+Buffer.from('owner:test-password-long-enough').toString('base64'),origin:server.url.origin,'content-type':'application/json'},body:JSON.stringify(body)}));
    expect(response.status).toBe(201); return response.json();
  };
  const scout = await request('/api/agents',{...defaults,name:'Scout',shape:'fox'});
  const offline = await request('/api/agents',{...defaults,name:'Writer',shape:'robot'});
  app.runtime.providers.get(scout.id).stop(); app.runtime.addProvider(scout.id,second);
  await app.runtime.refreshAccount(); await app.runtime.refreshAccount(scout.id); app.runtime.changed();
  const browser = await chromium.launch(), context = await browser.newContext({httpCredentials:{username:'owner',password:'test-password-long-enough'},viewport:{width:1440,height:960}});
  const page = await context.newPage(), errors = []; page.setDefaultTimeout(5000); page.on('pageerror',error=>errors.push(error.message));
  const artifacts = resolve(import.meta.dir,'../artifacts'); mkdirSync(artifacts,{recursive:true});
  const complete = (provider,job,text) => {
    provider.emit('notification',{method:'item/completed',params:{threadId:job.threadId,turnId:job.turnId,item:{id:randomUUID(),type:'agentMessage',text}}});
    provider.emit('notification',{method:'turn/completed',params:{threadId:job.threadId,turn:{id:job.turnId,status:'completed'}}});
  };
  try {
    await page.goto(server.url.href); await page.getByRole('heading',{name:'Message Pip',exact:true}).waitFor();
    await page.locator('#new-room').click(); await page.locator('#room-name').fill('Weekend council');
    await page.locator('#room-save').click(); expect(await page.locator('#room-status').textContent()).toContain('at least two');
    await page.locator(`#room-agent-options input[value="${scout.id}"]`).check();
    await page.screenshot({path:join(artifacts,'room-create.png'),fullPage:true});
    await page.locator('#room-save').click(); await page.locator('#room-label').filter({hasText:'Weekend council'}).waitFor();
    const room = app.runtime.state.conversations.find(c=>c.kind==='room');
    expect(await page.locator('#room-header').isVisible()).toBe(false);
    expect(await page.locator('#agent-dock').isVisible()).toBe(false);
    await page.locator('#room-details-open').click();
    expect(await page.locator('#room-members .room-member').count()).toBe(2);
    expect(await page.locator('#room-header').isVisible()).toBe(true);
    await page.getByRole('button',{name:'Close room details',exact:true}).click();
    expect(await page.locator('#room-details-open').evaluate(node=>node===document.activeElement)).toBe(true);
    await page.locator('#room-details-open').click(); await page.locator('#rename-room').click();
    await page.locator('#conversation-name').fill('Canceled room name'); await page.keyboard.press('Escape');
    expect(room.title).toBe('Weekend council');
    expect(await page.locator('#room-details-open').evaluate(node=>node===document.activeElement)).toBe(true);
    await page.locator('#room-details-open').click(); await page.locator('#rename-room').click();
    await page.locator('#conversation-name').fill('Weekend council renamed'); await page.locator('#rename-save').click();
    await page.locator('#room-label').filter({hasText:'Weekend council renamed'}).waitFor();
    expect(room.memberIds).toEqual([primary,scout.id]); expect(room.messages).toHaveLength(0);
    expect(await page.locator('#reply-agent option').evaluateAll(nodes=>nodes.map(n=>n.value))).toEqual(['all',primary,scout.id]);
    expect(await page.locator('#reply-agent').inputValue()).toBe('all');
    expect(await page.locator('.permission-picker').isVisible()).toBe(true);
    await page.locator('#interaction-mode').selectOption('safe');
    expect(await page.locator('#schedule-open').isVisible()).toBe(true);
    await page.locator('#schedule-open').click();
    expect(await page.locator('#schedule-agent option').count()).toBe(2);
    expect(await page.locator('#schedule-agent').inputValue()).toBe(primary);
    await page.keyboard.press('Escape');
    await page.locator('#prompt').fill('Compare weekend plans'); await page.locator('#prompt').press('Enter');
    await page.locator('#messages .message-user').waitFor(); await app.runtime.drain();
    await page.locator('#room-details-open').click(); expect(await page.locator('#delete-room').isDisabled()).toBe(true); await page.keyboard.press('Escape');
    const jobs = app.runtime.state.jobs.filter(j=>j.conversationId===room.id).reverse();
    expect(room.messages.filter(m=>m.role==='user')).toHaveLength(1); expect(jobs).toHaveLength(2);
    expect(jobs.every(j=>j.interactionMode==='safe')).toBe(true);
    complete(first,jobs[0],'Pip suggests Kyoto.'); await app.runtime.drain();
    await page.locator('.working-row strong').filter({hasText:'Scout'}).waitFor();
    complete(second,jobs[1],'Scout agrees; compare transport costs.');
    await page.getByText('Scout agrees; compare transport costs.',{exact:true}).waitFor();
    expect(await page.locator('.message-assistant .message-meta strong').allTextContents()).toEqual(['Pip','Scout']);
    await page.locator('#view').evaluate(node=>node.scrollTo({top:0,behavior:'instant'}));
    await page.screenshot({path:join(artifacts,'room-conversation.png'),fullPage:true});
    expect(second.calls.find(c=>c.method==='thread/start').params.developerInstructions).toContain('Pip suggests Kyoto.');
    await page.locator('#reply-agent').selectOption(scout.id);
    expect(await page.locator('.permission-picker').isVisible()).toBe(true);
    await page.locator('#prompt').fill('Scout, check costs'); await page.locator('#prompt').press('Enter');
    await page.getByText('Scout, check costs',{exact:true}).waitFor(); await app.runtime.drain();
    expect(app.runtime.state.jobs[0].agentId).toBe(scout.id); expect(app.runtime.state.jobs[0].discussionOnly).toBeUndefined();
    await page.getByRole('button',{name:'Stop discussion',exact:true}).click();
    await page.waitForFunction(()=>!document.querySelector('#send-button').disabled);
    await page.locator('#prompt').fill('Compare travel costs'); await page.locator('#room-details-open').click(); await page.locator('#room-discuss').click();
    expect(await page.locator('#room-header').isVisible()).toBe(false);
    await page.getByText('Compare travel costs',{exact:true}).waitFor();
    const next = app.runtime.state.jobs.slice(0,2); expect(next.every(j=>j.prompt==='Compare travel costs')).toBe(true);
    await page.getByRole('button',{name:'Stop discussion',exact:true}).click();
    await page.waitForFunction(()=>!document.querySelector('#edit-room').disabled);
    expect(next.every(j=>j.status==='cancelled')).toBe(true);
    await page.locator('#room-details-open').click(); await page.locator('#edit-room').click(); await page.locator('#room-name').fill('Weekend planning');
    await page.locator(`#room-agent-options input[value="${offline.id}"]`).check(); await page.locator('#room-save').click();
    await page.locator('#room-label').filter({hasText:'Weekend planning'}).waitFor();
    await page.locator('#prompt').fill('Discuss hotels'); await page.locator('#prompt').press('Enter');
    await page.locator('#toast').filter({hasText:'Connect Writer'}).waitFor();
    expect(await page.locator('#prompt').inputValue()).toBe('Discuss hotels');
    expect(room.messages.filter(m=>m.text==='Discuss hotels')).toHaveLength(0);
    await page.reload(); await page.locator('#room-label').filter({hasText:'Weekend planning'}).waitFor();
    expect(await page.locator('#room-members .room-member').count()).toBe(3);
    for (const width of [320,768,1024,1440]) {
      await page.setViewportSize({width,height:900});
      if (width<=760) await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
      expect(await page.locator('#room-header').isVisible()).toBe(false);
      expect(await page.locator('#agent-dock').isVisible()).toBe(false);
      const chatBox=await page.locator('#view').boundingBox(), composerBox=await page.locator('#composer').boundingBox();
      expect(chatBox.height).toBeGreaterThan(600);
      expect(composerBox.x+composerBox.width).toBeLessThanOrEqual(width);
      const sendBox=await page.locator('#send-button').boundingBox();
      expect(sendBox.x+sendBox.width).toBeLessThanOrEqual(width);
      await page.locator('#view').evaluate(node=>node.scrollTo({top:0,behavior:'instant'}));
      await page.screenshot({path:join(artifacts,`room-${width}.png`),fullPage:true});
      await page.locator('#room-details-open').focus(); await page.keyboard.press('Enter');
      expect(await page.locator('#room-header').evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);
      const detailsBox=await page.locator('#room-header').boundingBox(),editBox=await page.locator('#edit-room').boundingBox();
      expect(detailsBox.x).toBeGreaterThanOrEqual(0); expect(detailsBox.x+detailsBox.width).toBeLessThanOrEqual(width);
      expect(editBox.x+editBox.width).toBeLessThanOrEqual(width);
      await page.screenshot({path:join(artifacts,`room-details-${width}.png`)});
      await page.keyboard.press('Escape');
      expect(await page.locator('#room-header').isVisible()).toBe(false);
      expect(await page.locator('#room-details-open').evaluate(node=>node===document.activeElement)).toBe(true);
    }
    await page.locator('#room-details-open').click(); await page.locator('#edit-room').click(); await page.locator('#room-name').fill('Unsaved name'); await page.keyboard.press('Escape');
    expect(await page.locator('#room-heading').textContent()).toBe('Weekend planning');
    await page.locator('#close-conversation').click(); await page.waitForFunction(()=>document.querySelector('#room-details-open').hidden);
    await page.locator('#room-list [data-conversation]').click(); await page.locator('#room-details-open').waitFor({state:'visible'});
    await page.waitForFunction(()=>!document.querySelector('#minimize-agent').disabled);
    await page.locator('#new-chat').click(); expect(await page.locator('#room-details-open').isVisible()).toBe(false);
    expect(await page.locator('#agent-dock').evaluate(node=>node.hidden)).toBe(false);
    expect(await page.locator('#reply-agent option[value=all]').count()).toBe(0);
    const ordinary=await request('/api/jobs',{prompt:'Original chat title',agentId:primary}); await app.runtime.drain();
    complete(first,app.runtime.state.jobs.find(j=>j.id===ordinary.id),'Saved chat answer');
    await page.locator(`#history [data-conversation="${ordinary.conversationId}"]`).click();
    await page.locator('#page-title').filter({hasText:'Original chat title'}).waitFor();
    await page.locator('#page-title').click(); await page.locator('#conversation-name').fill('Weekend notes');
    await page.locator('#rename-save').click(); await page.locator('#page-title').filter({hasText:'Weekend notes'}).waitFor();
    expect(await page.locator('#messages').getByText('Saved chat answer',{exact:true}).isVisible()).toBe(true);
    await page.reload(); await page.locator('#page-title').filter({hasText:'Weekend notes'}).waitFor();
    expect(app.runtime.state.conversations.find(c=>c.id===ordinary.conversationId).title).toBe('Weekend notes');
    await page.locator('#page-title').click();
    page.once('dialog',dialog=>dialog.dismiss()); await page.locator('#delete-conversation').click();
    expect(app.runtime.state.conversations.some(c=>c.id===ordinary.conversationId)).toBe(true);
    page.once('dialog',dialog=>dialog.accept()); await page.locator('#delete-conversation').click();
    await page.locator('#rename-dialog').waitFor({state:'hidden'});
    await page.getByRole('heading',{name:'Message Pip',exact:true}).waitFor();
    expect(app.runtime.state.conversations.some(c=>c.id===ordinary.conversationId)).toBe(false);
    expect(app.runtime.state.jobs.some(j=>j.conversationId===ordinary.conversationId)).toBe(false);
    expect(await page.locator(`#history [data-conversation="${ordinary.conversationId}"]`).count()).toBe(0);
    await page.locator(`#room-list [data-conversation="${room.id}"]`).click(); await page.locator('#room-details-open').click();
    page.once('dialog',dialog=>dialog.dismiss()); await page.locator('#delete-room').click();
    expect(app.runtime.state.conversations.some(c=>c.id===room.id)).toBe(true);
    page.once('dialog',dialog=>dialog.accept()); await page.locator('#delete-room').click();
    await page.locator('#room-header').waitFor({state:'hidden'});
    await page.getByRole('heading',{name:/^Message /}).waitFor();
    expect(app.runtime.state.conversations.some(c=>c.id===room.id)).toBe(false);
    expect(app.runtime.state.jobs.some(j=>j.conversationId===room.id)).toBe(false);
    expect(await page.locator('#room-list [data-conversation]').count()).toBe(0);
    expect(app.runtime.state.agents).toHaveLength(3);
    await page.reload(); await page.getByRole('heading',{name:/^Message /}).waitFor();
    expect(await page.locator('#history [data-conversation],#room-list [data-conversation]').count()).toBe(0);
    expect(errors).toEqual([]);
  } finally {await browser.close(); await server.stop(); await app.close(); rmSync(directory,{recursive:true,force:true});}
},30_000);
